name: baseproject
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.3.0
  new_version_plus: ^0.0.11
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.1
  fluttertoast: ^8.2.8
  rounded_loading_button_plus: ^3.0.1
  firebase_analytics: ^11.2.1
  path_provider: ^2.0.12
  intl: ^0.19.0
  firebase_storage: ^12.2.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  get: ^4.6.6
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.7.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
