// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHey73TMkG29y9NcU0vwxNBQDGz1aiW0',
    appId: '1:914367519794:web:f601585be206173761f02b',
    messagingSenderId: '914367519794',
    projectId: 'baseapp-8852c',
    authDomain: 'baseapp-8852c.firebaseapp.com',
    storageBucket: 'baseapp-8852c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBud6kdu4MD9M1SBQ3pFZ4VQ0WMZ4G3Ufc',
    appId: '1:914367519794:android:d49420f4626455f761f02b',
    messagingSenderId: '914367519794',
    projectId: 'baseapp-8852c',
    storageBucket: 'baseapp-8852c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD95G_PnmSk59B-QkOgbBLCG6XwAVcpXwA',
    appId: '1:914367519794:ios:bfec685f96bc65bd61f02b',
    messagingSenderId: '914367519794',
    projectId: 'baseapp-8852c',
    storageBucket: 'baseapp-8852c.firebasestorage.app',
    iosClientId: '914367519794-5uimlq7k13sfpt83tgo2ekm4af8nh3uq.apps.googleusercontent.com',
    iosBundleId: 'com.baseproject.baseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD95G_PnmSk59B-QkOgbBLCG6XwAVcpXwA',
    appId: '1:914367519794:ios:bfec685f96bc65bd61f02b',
    messagingSenderId: '914367519794',
    projectId: 'baseapp-8852c',
    storageBucket: 'baseapp-8852c.firebasestorage.app',
    iosClientId: '914367519794-5uimlq7k13sfpt83tgo2ekm4af8nh3uq.apps.googleusercontent.com',
    iosBundleId: 'com.baseproject.baseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqHey73TMkG29y9NcU0vwxNBQDGz1aiW0',
    appId: '1:914367519794:web:1eef395d68428b8d61f02b',
    messagingSenderId: '914367519794',
    projectId: 'baseapp-8852c',
    authDomain: 'baseapp-8852c.firebaseapp.com',
    storageBucket: 'baseapp-8852c.firebasestorage.app',
  );
}
